### ISSUE TITLE
Instance Name indication in the Port Declaration

### ISSUE THREAD

**Issue by ldm1417** [ToTamire/HDL_Automation#1]
Hi All,

I'm working with the modules, which have a long list of the ports. So, without scrolling the Editor window up (to the line where the module is instantioned), it's hard to understand what module/instance the observed port belongs to. 

Is it possible to add a tooltip, which would show the instance name the pointed/selected port belongs to? 

So, as for me, I see at least two solutions to the problem:
1) adding a tooltip to the port name, which would indicate what module name the current port belongs to
2) Syncing the Editor to Outline Panel (syncing in the opposite direction (Output Panel to Editor) it's already exists). So, clicking on the port will highlight the instance name in the Outline Panel

But honestly I don't know how to implement the above solutions... Does anybody know? Are there another solutions to this problem? 

As for me this feature is critical because I'm working with the instances, which usually have a very long list of the ports.

Thank you in advance!

**Comment by ToTamire** [comment]
I don't think I get it.

Do you have few modules inside one file and you want to know in which module you are?
![image](https://user-images.githubusercontent.com/71039587/151999610-0374a1c5-26ef-49df-ab6b-94d3a95145b8.png)

Or you have few module instances inside one module and you want to know in which instance you are?
![image](https://user-images.githubusercontent.com/71039587/151999838-ef32b6db-620f-4206-a535-3fa31089d784.png)

**Comment by ldm1417** [comment]
Hi, 

 

Exactly… You correctly caught the issue…  When I point to a port of the intentioned module, I’d like to see a tooltip with the instantiated module name (like in the picture below). 

 

  <https://user-images.githubusercontent.com/71039587/151999838-ef32b6db-620f-4206-a535-3fa31089d784.png> 

 

Thanks!

**Comment by ldm1417** [comment]
Yes, I have several instantiations of several modules inside one file... When I hover a mouse over the instance port, I'd like to see the instance/module name in the tooltip.

**Comment by ToTamire** [comment]
Version 1.2.0 is now aviable in Package Control.

![scope_name](https://user-images.githubusercontent.com/71039587/152976889-fc0db18e-7037-43b5-b3b7-e69e24c8c4a3.gif)
